### ISSUE TITLE
Add operator `<~`

### ISSUE THREAD

**Issue by geonu1109** [RxSwiftCommunity/RxBinding#3]
There is already an operator `~>` what bind observable to observer.

How about add an operator `<~` what bind observer by observable?

**Comment by lm2343635** [comment]
I am not sure what you want to implement.
You mean
`a <~ b` == `b.bind(to: a)` ??

**Comment by geonu1109** [comment]
`a <~ b` == `b.bind(to: a)`
Correct! It's what I want to say.

**Comment by xueyongwei** [comment]
No nessary.

**Comment by lm2343635** [comment]
I think adding the operator `<~` makes the operators confused to understand.
Because we have a two-way binding operator `<~>`.
Even it is a two-way binding operator, we have to use it according to order, just like:
```swift
BehaviorRealy <~> ControlValue
```
You can confirm the implementation of the two way binding method.
The operator `<~` makes it possible to reverse the binder and observable object.
However, I do not hope to reverse for the operator `<~>`.
For this reason, close this issue.
